services:
  db:
    image: postgres:latest
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"